version: '2'
services:
  dash-app:
    image: python:3.7
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install dash dash_core_components dash_html_components plotly numpy statistics && python app.py"
    ports:
      - '3000'
    environment:
      - VIRTUAL_HOST=applestory.egylogic.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=applestory.egylogic.com
      - LETSENCRYPT_EMAIL=info@egylogic.com
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
      name: nginx-proxy
      external: true
